rails_blog/config/routes.rb
RailsBlog::Application.routes.draw do

  resources :posts
  resources :comments

  get '/' => 'posts#index'

end

rails_blog/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

rails_blog/app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
end

rails_blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
	end

	def new
		@comment = Comment.new
	end

	def create
		post = Post.find(session[:post_id])
		comment = Comment.new(comment_params)
		post.comments << comment
		redirect_to post
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end
end

rails_blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.create(user_params)
		redirect_to @post
	end

	def show
		@post = Post.find(params[:id])
	end

	private 

	def user_params
		params.require(:post).permit(:title, :content)
	end
end


#params.require(:user).permit(:username, :email, :password, :salt, :encrypted_password)

rails_blog/app/views/comments/new.html.erb
<div class="container">
	<%= form_for @comment, url: {action: "create"} do |f| %>
		<%= f.text_area :content, placeholder: "Type here" %>
		<%= f.submit "Comment" %>
	<%end%>
</div>

rails_blog/app/views/posts/index.html.erb
<div class="container">
	<h1 class="site-title">Anon Blog</h1>
	<%=link_to "Create Post", new_post_path%>	

	<ul>
		<% @posts.each do |post| %>
			<li class="title"><%=link_to post.title, post_path(post.id) %> </li>
			<li class="content"><%= post.content %></li>
			<li class="comment-count"> -- <%= post.comments.length %> Comments</li><br>
		<%end%>
	</ul>
</div>

rails_blog/app/views/posts/new.html.erb
<div class="container">
	<h1>Create a post</h1>
	<%= form_for @post, url: {action: "create"} do |f| %>
		<%= f.text_field :title, placeholder: "Title" %>
		<%= f.text_area :content, placeholder: "Blog here" %>
		<%= f.submit "Create" %>
	<%end%>
</div>

rails_blog/app/views/posts/show.html.erb
<div class="container">
	<%= link_to "Home", posts_path%>
	<h2 class="title"><%= @post.title %></h2>
	<p class="content"><%= @post.content %></p>
	<%= link_to "Add Comment", new_comment_path%>

	<h3>Comments: </h3>
	<ul class="list-coments">
		<% @post.comments.each do |comment| %>
			<li class="comment"><%=comment.content%> -- <span class="time"><%=comment.created_at%></span></li>
		<%end%>
	</ul>

	<% session[:post_id] = @post.id %>
</div>