reddit_jr_rails/config/routes.rb
RedditJrRails::Application.routes.draw do

  root 'posts#index'

  # DELETE 'sessions#destroy'

  resources :users do 
    resources :posts
  end

  resources :posts do
    resources :comments
  end

  resources :sessions
end

reddit_jr_rails/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user

end

reddit_jr_rails/app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	belongs_to :user
end

reddit_jr_rails/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates_uniqueness_of :username
	has_many :posts
	has_many :comments, through: :posts
end

reddit_jr_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

reddit_jr_rails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		@comment = Comment.new
	end

	def create
		@comment = Comment.create(content: params[:comment][:content], user_id: session[:current_user], post_id: params[:post_id])
		redirect_to post_path(params[:post_id])
	end
end

reddit_jr_rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to posts_path
		else
			render :new
		end
	end


	private 

	def post_params
		params.require(:post).permit(:title, :content, :score)
	end
end

reddit_jr_rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_username(params[:session][:username])

		if user.authenticate(params[:session][:password])
			session[:current_user] = user.id
			redirect_to posts_path
		else
			render :new
		end
	end

	def destroy
		session[:current_user] = nil
		redirect_to posts_path
	end

end

reddit_jr_rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to posts_path
		else
			render :new
		end
	end

	private

	def user_params
		params.require(:user).permit(:username, :password, :password_confirmation)
	end
end

reddit_jr_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_jr_rails/app/views/comments/new.html.erb
<div class="container">
	<h2>Add Comment</h2>

	<%= form_for @comment, url: {action: "create"} do |f| %>
		<%=f.label "content"%>
			<%=f.text_field :content%>
		<%=f.submit%>
	<%end%>
</div>

reddit_jr_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditJrRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

reddit_jr_rails/app/views/posts/index.html.erb
<div class="container">
	<h1>Reddit Jr Rails Yo</h1>

	<% if session[:current_user]%>

	<h1>Welcome <%=User.find(session[:current_user]).username%></h1>
	<%end%>

		

		<% if session[:current_user] %>
			<%= link_to "Sign Out", session_path(session[:current_user]), :method=>:delete %>
		<% else %>
			<%= link_to "Sign Up", new_user_path%>
			<%= link_to "Sign In", new_session_path%>
		<%end%>
	
		<%= link_to "Create Post", new_post_path%>
	<ul class="list-posts">
		<% @posts.each do |post| %>
			<li><%= link_to "#{post.title}" , post_path(post.id) %>Score: <%=post.score%></li>
		<%end%>
	</ul>

</div>

reddit_jr_rails/app/views/posts/new.html.erb
<div class="container">
	<h2>Create a new post</h2>
	<%= form_for @post do |f| %>
		<%= f.label "title"%>
			<%= f.text_field :title, placeholder: "Title", autofocus:  :true %><br>
		<%= f.label "content"%>
			<%= f.text_area :content, placeholder: "Type here" %><br>
		<%= f.submit %>
	<%end%>
</div>

reddit_jr_rails/app/views/posts/show.html.erb
<div class="container">
	<%=link_to "Home", posts_path%>

	<h2><%=@post.title%></h2>
		<h4><%=@post.content%></h4>

		<h3>Comments: </h3>
			<ul class="comment-list">
				<%@post.comments.each do |comment| %>
					<li><%=comment.content%></li>
					<li><%=comment.user.username%></li>
				<%end%>
			</ul>

	<%= link_to "Add Comment", new_post_comment_path(@post) %>


</div>

reddit_jr_rails/app/views/users/new.html.erb
<div class="container">
	<h2>Create an Account</h2>
	<%= form_for @user do |f| %>
		<%= f.label "username"%>
			<%= f.text_field :username, placeholder: "Username", autofocus: :true%><br>
		<%= f.label "password"%>
			<%= f.password_field :password, placeholder: "Password" %><br>
		<%= f.label "Confirm Password" %>
			<%= f.password_field :password_confirmation, placeholder: "Confirm Password" %><br>
		<%= f.submit %>
		<%end%>
</div>